### ISSUE TITLE
Question: Plugin support

### ISSUE THREAD

**Issue by babsonmatt** [reactbits/markdown#24]
Any plans to support plugins for this library itself, or would they just be implemented through markdown-it plugins?

Also wondering, any ideas how one might implement something to use something like react-router's Link so that certain links can be loaded within the app itself and not cause a full page reload?

Thanks!

**Comment by sergeyt** [comment]
hi @babsonmatt, my current vision is to allow use of markdown-it plugins adding some extension point where they are registered in this library. re react-router links: I also need this functionality soon, and this is feasible to do as linkify plugins maybe adjusting rendering of links with customizable navigation behavior.

**Comment by babsonmatt** [comment]
Thanks for the info @sergeyt

**Comment by sergeyt** [comment]
@babsonmatt BTW it would be great if someone (maybe me :)) creates reactjs renderer for markdown-it, see also [this thread](https://github.com/markdown-it/markdown-it/issues/141).

**Comment by babsonmatt** [comment]
Right now I'm using https://github.com/alexkuz/markdown-react-js#using-custom-component-renderer which has some support for custom component rendering - for example I'm using it to replace links on the site to Link tags for use with react-router - but it still uses dangerouslySetInnerHTML (not sure if you're planning to try to implement without that or if eliminating that would be useful?

**Comment by sergeyt** [comment]
I think having pure reactjs renderer (eliminating `dangerouslySetInnerHTML`) could bring good performance for use case when you try to edit large markdown document with real-time preview.
